# Generated by Django 5.2.4 on 2025-07-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('restaurant', 'DONOR'), ('ngo', 'NGO')], max_length=20),
        ),
    ]
