# Generated by Django 5.2.4 on 2025-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fooddonation_claimed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
