# Generated by Django 5.2.4 on 2025-07-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fooddonation_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_photos/'),
        ),
    ]
