# Generated by Django 5.2.4 on 2025-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fooddonation_delivered_fooddonation_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=11),
        ),
    ]
